// examples/nuxt/components/SessionsFlow.vue
<script lang="ts">
import { DEFAULT_AMOUNT } from '~/constants';
import { AdyenCheckout, Dropin } from '@adyen/adyen-web/auto';
import type { AdyenCheckoutError, CoreConfiguration, PaymentCompletedData, PaymentFailedData, UIElement } from '@adyen/adyen-web/auto'
import '@adyen/adyen-web/styles/adyen.css';

export default {
    data() {
        return {
            dropin: null as Dropin | null,
        };
    },

    async mounted() {
        this.createCheckout();
    },

    methods: {
        async createCheckout() {
            const urlParams = new URLSearchParams(window.location.search);
            const countryCode = urlParams.get('countryCode') || 'US';
            const locale = urlParams.get('shopperLocale') || 'en-US';
            const amount = parseAmount(urlParams.get('amount') || DEFAULT_AMOUNT, countryCode);

            const runtimeConfig = useRuntimeConfig();
            const { id, sessionData } = await createSession(countryCode, locale, amount);

            const options: CoreConfiguration = {
                session: {
                    id,
                    sessionData
                },
                amount,
                countryCode,
                locale,
                environment: 'test',
                clientKey: runtimeConfig.public.clientKey,
                onPaymentCompleted(data: PaymentCompletedData, element?: UIElement) {
                    console.log('onPaymentCompleted', data, element);
                },
                onPaymentFailed(data: PaymentFailedData, element?: UIElement) {
                    console.log('onPaymentFailed', data, element);
                },
                onError(error: AdyenCheckoutError) {
                    console.error('Something went wrong', error);
                },
            };

            const checkout = await AdyenCheckout(options);

            this.dropin = new Dropin(checkout, {
                paymentMethodsConfiguration: {
                    card: {
                        _disableClickToPay: true
                    }
                }
            });
            this.dropin.mount(this.$refs.dropinRef as HTMLElement);
        }
    }
};
</script>

<template>
    <div>
        <div class="payment" ref="dropinRef"></div>
    </div>
</template>

<style scoped>
.payment {
    margin: auto;
    max-width: 800px;
}
</style>

// examples/nextjs/app/_components/sessions-flow/sessions-flow.tsx
"use client";

import { useCallback, useEffect, useRef } from "react";
import { useSearchParams } from "next/navigation";
import {
    AdyenCheckout,
    Dropin,
    Card,
    CashAppPay,
    GooglePay,
    PayPal,
    UIElement,
    AdyenCheckoutError,
} from "@adyen/adyen-web";
import "@adyen/adyen-web/styles/adyen.css";
import type {
    PaymentFailedData,
    PaymentCompletedData,
    CoreConfiguration,
    DropinConfiguration,
} from "@adyen/adyen-web";
import {
    DEFAULT_AMOUNT,
    DEFAULT_COUNTRY,
    DEFAULT_LOCALE,
} from "@/app/_utils/constants";
import makeSessionsSetupCall from "../../_utils/makeSessionsSetupCall";
import { parseAmount } from "@/app/_utils/amount-utils";

export default function SessionsFlow() {
    const dropinRef = useRef<HTMLDivElement>(null);
    const isAdyenWebInitialized = useRef<boolean>(false);
    const searchParams = useSearchParams();

    const loadAdyen = useCallback(async () => {
        const countryCode = searchParams.get("countryCode") || DEFAULT_COUNTRY;
        const locale = searchParams.get("shopperLocale") || DEFAULT_LOCALE;
        const amount = parseAmount(
            searchParams.get("amount") || DEFAULT_AMOUNT,
            countryCode,
        );

        const session = await makeSessionsSetupCall({
            countryCode,
            amount,
            shopperLocale: locale,
        });

        const options: CoreConfiguration = {
            clientKey: process.env.NEXT_PUBLIC_CLIENT_KEY,
            session: {
                id: session.id,
                sessionData: session.sessionData,
            },
            countryCode,
            amount,
            locale,
            environment: "test",
            analytics: {
                enabled: false,
            },
            onError(error: AdyenCheckoutError) {
                console.error("Something went wrong", error);
            },
            onPaymentCompleted(data: PaymentCompletedData, element: UIElement) {
                console.log(data, element);
            },
            onPaymentFailed(data: PaymentFailedData, element: UIElement) {
                console.log(data, element);
            },
        };

        const checkout = await AdyenCheckout(options);

        const dropinConfiguration: DropinConfiguration = {
            paymentMethodsConfiguration: {
                card: {
                    _disableClickToPay: true,
                },
            },
            paymentMethodComponents: [Card, PayPal, CashAppPay, GooglePay],
        };

        if (dropinRef.current) {
            new Dropin(checkout, dropinConfiguration).mount(dropinRef.current);
        }
    }, [searchParams]);

    useEffect(() => {
        if (!isAdyenWebInitialized.current) {
            isAdyenWebInitialized.current = true;
            void loadAdyen();
        }
    }, [loadAdyen]);

    return <div ref={dropinRef} id="dropin"></div>;
}
